.PHONY: demo

demo:
	@echo "kubectl port-forward -n monitoring svc/kube-prometheus-stack-prometheus 9090:9090& \\ \n\
	kubectl port-forward -n monitoring svc/kube-prometheus-stack-alertmanager 9093:9093&"
